# Find Alvar
#
# This module defines
# ALVAR_FOUND:           true if found
# ALVAR_INCLUDE_DIR:     Where to find Alvar.h
# ALVAR_LIBRARIES:       alvar libraries to link to

FIND_PATH(ALVAR_INCLUDE_DIR Alvar.h
    PATHS
        $ENV{PROGRAMFILES}
        $ENV{ALVARDIR}
        $ENV{ALVAR_DIR}
        /usr
        /usr/local
        /sw
        /opt/local
    PATH_SUFFIXES
        /include
)

MACRO(FIND_ALVAR_LIBRARY_RELEASE MYLIBRARY MYLIBRARYNAME)
FIND_LIBRARY(${MYLIBRARY}
    NAMES
        ${MYLIBRARYNAME}
    PATHS
        $ENV{ALVARDIR}
        $ENV{ALVAR_DIR}
        /usr
        /usr/local
        /sw
        /opt/local
    PATH_SUFFIXES
        /lib
        /lib64
        /lib/Release
)
ENDMACRO(FIND_ALVAR_LIBRARY_RELEASE MYLIBRARY MYLIBRARYNAME)

MACRO(FIND_ALVAR_LIBRARY_DEBUG MYLIBRARY MYLIBRARYNAME)
FIND_LIBRARY(${MYLIBRARY}
    NAMES
        ${MYLIBRARYNAME}
    PATHS
        $ENV{ALVARDIR}
        $ENV{ALVAR_DIR}
        /usr
        /usr/local
        /sw
        /opt/local
    PATH_SUFFIXES
		/bin
        /lib
        /lib64
        /lib/Debug
)
ENDMACRO(FIND_ALVAR_LIBRARY_DEBUG MYLIBRARY MYLIBRARYNAME)

FIND_ALVAR_LIBRARY_RELEASE(ALVAR_LIBRARY_RELEASE alvar200)
FIND_ALVAR_LIBRARY_DEBUG(ALVAR_LIBRARY_DEBUG alvar200d)

#FIND_ALVAR_LIBRARY_RELEASE(ARTOOLKIT_GSUBLITE_LIBRARY_RELEASE ARgsub_lite)
#FIND_ALVAR_LIBRARY_DEBUG(ARTOOLKIT_GSUBLITE_LIBRARY_DEBUG ARgsub_lite)

SET(ALVAR_FOUND "NO")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALVAR DEFAULT_MSG ALVAR_LIBRARY_RELEASE ALVAR_INCLUDE_DIR)

IF(ALVAR_FOUND)
    IF(ALVAR_LIBRARY_DEBUG)
        SET(ALVAR_LIBRARIES optimized ${ALVAR_LIBRARY_RELEASE} debug ${ALVAR_LIBRARY_DEBUG})
    ELSE(ALVAR_LIBRARY_DEBUG)
        SET(ALVAR_LIBRARIES ${ALVAR_LIBRARY_RELEASE})
    ENDIF(ALVAR_LIBRARY_DEBUG)
ENDIF(ALVAR_FOUND)
