# Find Bonjour
#
# This module defines
# BONJOUR_FOUND:           true if found
# BONJOUR_INCLUDE_DIR:     Where to find dns_sd.h
# BONJOUR_LIBRARIES:       bonjour libraries to link to

FIND_PATH(BONJOUR_INCLUDE_DIR dns_sd.h
    PATHS
        $ENV{PROGRAMFILES}
        $ENV{BONJOURDIR}
        $ENV{BONJOUR_DIR}
        /usr
        /usr/local
        /sw
        /opt/local
    PATH_SUFFIXES
        /include
)

MACRO(FIND_BONJOUR_LIBRARY_X64 MYLIBRARY MYLIBRARYNAME)
FIND_LIBRARY(${MYLIBRARY}
    NAMES
        ${MYLIBRARYNAME}
    PATHS
        $ENV{PROGRAMFILES}
        $ENV{BONJOURDIR}
        $ENV{BONJOUR_DIR}
        /usr
        /usr/local
        /sw
        /opt/local
    PATH_SUFFIXES
        /lib
        /lib64
        /Lib/x64
)
ENDMACRO(FIND_BONJOUR_LIBRARY_X64 MYLIBRARY MYLIBRARYNAME)

MACRO(FIND_BONJOUR_LIBRARY_X86 MYLIBRARY MYLIBRARYNAME)
FIND_LIBRARY(${MYLIBRARY}
    NAMES
        ${MYLIBRARYNAME}
    PATHS
        $ENV{PROGRAMFILES}
        $ENV{BONJOURDIR}
        $ENV{BONJOUR_DIR}
        /usr
        /usr/local
        /sw
        /opt/local
    PATH_SUFFIXES
        /lib
        /lib64
        /Lib/Win32
)
ENDMACRO(FIND_BONJOUR_LIBRARY_X86 MYLIBRARY MYLIBRARYNAME)

# Bonjour SDK on windows contains both 32 and 64 bit libraries. Adjust the library search path
# based on the bit-ness of the build.
IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET(IS_X64 TRUE)
ELSE(CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET(IS_X64 FALSE)
ENDIF(CMAKE_SIZEOF_VOID_P EQUAL 8)

IF(WIN32)
    IF(IS_X64)
        FIND_BONJOUR_LIBRARY_X64(BONJOUR_LIBRARY_RELEASE dnssd)
    ELSE(IS_X64)
        FIND_BONJOUR_LIBRARY_X86(BONJOUR_LIBRARY_RELEASE dnssd)
    ENDIF(IS_X64)
ELSE(WIN32)
    IF(NOT APPLE)
        IF(IS_X64)
            FIND_BONJOUR_LIBRARY_X64(BONJOUR_LIBRARY_RELEASE dns_sd)
        ELSE(IS_X64)
            FIND_BONJOUR_LIBRARY_X86(BONJOUR_LIBRARY_RELEASE dns_sd)
    ENDIF(IS_X64)
    ENDIF(NOT APPLE)
ENDIF(WIN32)

SET(BONJOUR_FOUND "NO")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BONJOUR DEFAULT_MSG BONJOUR_LIBRARY_RELEASE BONJOUR_INCLUDE_DIR)

IF(BONJOUR_FOUND)
    IF(BONJOUR_LIBRARY_DEBUG)
        SET(BONJOUR_LIBRARIES optimized ${BONJOUR_LIBRARY_RELEASE} debug ${BONJOUR_LIBRARY_DEBUG})
    ELSE(BONJOUR_LIBRARY_DEBUG)
        SET(BONJOUR_LIBRARIES ${BONJOUR_LIBRARY_RELEASE})
    ENDIF(BONJOUR_LIBRARY_DEBUG)
ENDIF(BONJOUR_FOUND)
